name: CI

on:
  # Run on all pull requests
  # Run on pushes to the main branch
  pull_request:
  push:
    branches: [ main ]
  # This makes the workflow reusable by other workflows
  workflow_call:

jobs:
  # This job scans for security vulnerabilities
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # This is required for bundle install to find the local 'core' gem
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true # Caches gems for faster builds

      - name: Scan for common Rails security vulnerabilities
        run: bin/brakeman --no-pager --no-exit-on-warn

  # This job checks for code style consistency
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # This is required for bundle install to find the local 'core' gem
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github
        continue-on-error: true

  # This job runs all your tests
  test:
    runs-on: ubuntu-latest
    # This job will only run if the scan and lint jobs succeed
    needs: [scan_ruby, lint]

    env:
      RAILS_ENV: test
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_HOST: localhost
      DB_PORT: 5434
      REDIS_URL: redis://localhost:6381/0
      FRONTEND_URL: http://localhost:3000
      PAGES_BASE_DOMAIN: example.com
      SECRET_KEY_BASE: replace_with_lengthy_secure_hex
      POSTMARK_X_API_KEY: test
      PGHOST: localhost
      PGUSER: test
      PGPASSWORD: test


    # This sets up a PostgreSQL database service for the job to use
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test # A name for the test database
        ports:
          - 5434:5432
        # Health check to ensure postgres is ready before steps run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6-alpine
        ports:
          - 6381:6379
        # Health check to ensure redis is ready before steps run
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code (including submodules)
        uses: actions/checkout@v5
        with:
          # IMPORTANT: This fetches your 'core' engine submodule code
          submodules: true

      - name: Install Base Packages
        run: |
          sudo apt-get update -qq && 
          sudo apt-get install --no-install-recommends -y curl nodejs libjemalloc2 libvips postgresql-client libvips

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Create .npmrc file
        run: echo "${{ secrets.NPMRC_FILE }}" > .npmrc

      - name: Install Packages
        run: |
          npm install -g bun &&
          bun install &&
          bundle install

      - name: Set up test database
        run: bin/rails db:setup

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run Host Application Tests
        run: bin/rails test

      - name: Run Core Engine Tests
        run: bin/rake test:core_engine
